# Generated by Django 6.0.3 on 2026-03-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('resource', 'Resource')], max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('description', models.CharField(choices=[('text extracted from resource', 'Text Extracted From Resource'), ('extracted text clean up finished', 'Extracted Text Clean Up Finished')], max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EventConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventconsumer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'consumer')},
            },
        ),
    ]
