# Generated by Django 6.0.3 on 2026-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventconsumed",
            name="exception",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventconsumed",
            name="status",
            field=models.CharField(
                choices=[("OK", "OK"), ("ERROR", "Error")], default="OK", max_length=10
            ),
        ),
    ]
