# Generated by Django 6.0.3 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_description_alter_event_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="triggered_by",
            field=models.CharField(default="backend", max_length=255),
        ),
    ]
