# Generated by Django 6.0.3 on 2026-03-08 18:30

from django.db import migrations


def populate_default_config(apps, schema_editor):
    TextExtractionConfig = apps.get_model("kb", "TextExtractionConfig")
    TextExtractionConfig.objects.get_or_create(
        title="JINA AI API",
        defaults={"details": {}}
    )

def reverse_populate(apps, schema_editor):
    TextExtractionConfig = apps.get_model("kb", "TextExtractionConfig")
    TextExtractionConfig.objects.filter(title="JINA AI API").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_textextractionconfig_secret_text_extraction_config'),
    ]

    operations = [
        migrations.RunPython(populate_default_config, reverse_populate),
    ]
