# Generated by Django 6.0.3 on 2026-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_alter_llmconfig_provider_resourcechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
