# Generated by Django 6.0.3 on 2026-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0012_knowledgegraphconfig_alter_llmconfig_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgegraphconfig",
            name="package_name",
            field=models.CharField(default="lightrag_app", max_length=255),
        ),
    ]
